dist: trusty
language: python
python:
  - 2.7
  - 3.6.1

env:
  - TF_VERSION=1.7.0
  - TF_VERSION=1.8.0
  - TF_VERSION=1.9.0
  - TF_VERSION=1.10.0
  - TF_VERSION=1.11.0
  - TF_VERSION=1.12.0
  - TF_VERSION=1.13.1

install:
  - pip install tensorflow==$TF_VERSION
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

script:
  - flake8 tensorrec
  - flake8 test
  - flake8 examples
  - nosetests --with-timer

notifications:
  email: false
